### ISSUE TITLE
Not showing Updates

### ISSUE THREAD

**Issue by leowys** [envato/envato-wordpress-toolkit#101]
Hello! Since a few weeks the toolkit not showing updates for themes, i'm using it with two different themes (The Retailer and Be Theme) in two different sites and no one shows updates. I've tried activating deactivating plugin, creating new API keys and nothing, the themes doesn't show any updates. Can you please help me? Thanks!

**Comment by siasat** [comment]
Same here. Update is not working. Please help.

**Comment by leowys** [comment]
Hello! No one else is having this issue?

**Comment by siasat** [comment]
I ended up installing my updated theme manually. The Envato Toolkit doesn't seem to work

**Comment by valendesigns** [comment]
This plugin was deprecated months ago and is not being updated.

I am building a new and better version that supports both themes and plugins, which is getting close to being released. There was a hold up with the new API that was addressed yesterday. For now I would suggest doing your updates manually if the plugin is not handling them for you. Sorry for the inconvenience you are having.

**Comment by leowys** [comment]
Thanks Derek! Can't wait to test the new plugin!
