### ISSUE TITLE
Move admin menu item to submenu

### ISSUE THREAD

**Issue by swinggraphics** [envato/envato-wordpress-toolkit#103]
Please move "Envato Toolkit" to a submenu under Appearance, Tools, or Settings. It does not belong in the top level.

**Comment by valendesigns** [comment]
This plugin will not be getting anymore updates. Though I would like to hear your argument for why it should be moved and consider it for the new plugin.

**Comment by swinggraphics** [comment]
? Because it isn't needed after initial configuration and shouldn't clutter up the menu. Tell me why it DOES deserve to be there.
