### ISSUE TITLE
Can't deactivate Envato Toolkit Plugin

### ISSUE THREAD

**Issue by jansilber2016** [envato/envato-wordpress-toolkit#160]
Trying to update the deprecated Toolkit Plugin there is no button for deactivate the plugin like in the picture:

![envato plugin](https://user-images.githubusercontent.com/38662585/39134364-be6ff56c-4716-11e8-883f-7087b392a704.PNG)

How can I deactivate the old plugin then?

**Comment by chisamna** [comment]
If you haven't already figured this out, you should be able to check the box next to it and then go to top and deactivate. Then go back to it and check again to delete. When I do it, though, it doesn't work, which is why I'm looking for answers on this forum.

**Comment by dtbaker** [comment]
Please ensure the latest version of WordPress is installed. 

Please ensure the latest version of the WordPress theme or plugin is installed (check http://themeforest.net/downloads to grab the latest item update if needed)

If running in multisite/network mode please ensure the plugin is deactivated on every sub-website before deleting the plugin from the main network site. 

If that still doesn't work please login to the website with FTP and go to the wp-content/plugins/ folder and rename the `envato-wordpress-toolkit` folder to `disabled-envato-toolkit` and it will disable in the backend.

**Comment by chisamna** [comment]
Thanks, I think this did the job.
