### ISSUE TITLE
Envato WordPress Toolkit - 'Environment error'.

### ISSUE THREAD

**Issue by dylanthomas2-github** [envato/envato-wordpress-toolkit#22]
Hello

I have a new WordPress Multisite installation (3.9.1) on a Domain on a Dedicated Server.

I get the following error:

"
Envato WordPress Toolkit

Environment error: Unable to increase maximum execution time. Due to settings on your server, large themes may be unable to update automatically. Please consult your server administrator if this causes issues for you. Dismiss this.

".

Can you please help by clarifying the cause of this error so that I can pass any remedies onto our ISP? Or, provide steps to solve?

Regards

**Comment by noaneo** [comment]
Hi,
Excuse me, I know an old message, but the same problem for a friend, he does not have access to php.ini
Can he do this with .htaccess?
With this code?
php_value max_execution_time 3000
Thank you and sorry again!
