### ISSUE TITLE
Fatal Error: Redeclare class Envato_WP_Toolkit

### ISSUE THREAD

**Issue by SirLouen** [envato/envato-wordpress-toolkit#47]
Cannot activate this plugin
Here is the error:

Fatal error: Cannot redeclare class Envato_WP_Toolkit in /web/wp-content/plugins/envato-wordpress-toolkit/index.php on line 10

**Comment by thinkertech** [comment]
Does anyone have an suggestion on how to fix this error?

.... wp-content/plugins/envato-wordpress-toolkit/index.php on line 10

**Comment by valendesigns** [comment]
It sounds like you have a theme active that uses the `envato-wordpress-toolkit-library` and also have the `envato-wordpress-toolkit` plugin activated. I'll add some checks to make sure the class doesn't load if it already exists.

**Comment by valendesigns** [comment]
This should be fixed in 1.7.2 please test that branch if you have time.
