### ISSUE TITLE
Installed via Wordpress backend.  Now site is completely inoperable.

### ISSUE THREAD

**Issue by solidusv1** [envato/envato-wordpress-toolkit#49]
Installed this as ti was listed as "requried" in my theme all of a sudden this morning.  Rendered my site completely inoperable.

**Comment by valendesigns** [comment]
What version are you using?

**Comment by solidusv1** [comment]
I received a message in the Wordpress backend saying this needed to be installed.  Brand new wordpress install as of yesterday...this message showed up this morning.  Installed, created envato API key on Envato site and poof...toast.

**Comment by valendesigns** [comment]
I was asking which version of the plugin not WP.

**Comment by solidusv1** [comment]
I'm sorry, I guess I don't have that information.  I installed it from the dialog in the backend of Wordpress that told me it was a required plugin as of this morning.  That dialog just showed up this morning...so I'm assuming most recent.

**Comment by valendesigns** [comment]
That dialogue could have been from I script that installs it from zip included in your theme. It's not 100% it's the most recent. Just rename the plugins directory to force it to deactivate and check which version is installed. =

**Comment by solidusv1** [comment]
I had already deleted the plugin folder to no effect.  But I looked in the theme files for the zip you mentioned and the readme has the most recent changelog as 1.7.1

**Comment by valendesigns** [comment]
If the plugin has already been removed than its likely a theme issue. Maybe it's missing some files. Rename your theme so it deactivates. =

**Comment by solidusv1** [comment]
No effect.  I have installed my backup and created a new DB with my backup.  Theme and site works fine without the envato toolkit installed.

**Comment by valendesigns** [comment]
When the plugin is removed it can't do anything to your site. It's impossible. There is an underlying issue here. Check your PHP error logs. =

**Comment by solidusv1** [comment]
I understand what you're saying....but after deleting the plugin folder to no effect, I uploaded my backups of the entire root folder to replace everything, including theme files and there was still no fix.  It didn't start working until I made a new database and imported the backup DB info into it.  I'll look at the logs.

**Comment by valendesigns** [comment]
Unfortunately, I can't troubleshoot this any further. If you have additional information to give me reopen the issue.
