### ISSUE TITLE
Our theme updates are not available for buyers

### ISSUE THREAD

**Issue by vivacomedia** [envato/envato-wordpress-toolkit#50]
Hello everyone, we have a strange issue with our item http://themeforest.net/item/startuply-multipurpose-startup-theme/9055667 and Envato Toolkit v1.7.1 - when setup with API keys it is no longer showing the latest Wordpress versions available and the clients can't update their themes from v1.0.4 to v1.4 one.. What has gone wrong is this something from our side or plugin's?

We have got an official Envato response to this that i cite below:
> Thanks for raising this. This problem sometimes occurs when the separate theme zip file (as 
> opposed to the main zip file) has the wrong version. However, I checked it for Startuply and it 
> appears to be version 1.4, so it's not that problem.
> We'll need to get the developer who maintains the Envato Toolkit plugin to look into the issue. The
> easiest way to do this is to create a new issue over on the GitHub repo

P.S. for example a buyer with nickname ****** doesn't have any update options for our theme (see screenshot attached) and we've got reports of the same issues from other buyers too..
![startuply_no_updates](https://cloud.githubusercontent.com/assets/452731/5935324/5a18af3c-a6e2-11e4-9733-b197485f3378.jpg)

Thanks a lot in advance!

**Comment by valendesigns** [comment]
I can't troubleshoot this issue without a verified buyers username, and API key. Plus a copy of the previous version of the theme, so I can try and duplicate the same environment. If you can supply those things to test this issue, my email is derek@valendesigns.com

I also need to know what WP, and PHP versions you're using.

Cheers,
Derek

**Comment by vivacomedia** [comment]
Hello Derek,

and thanks for your response i highly doubt the customer will provide me
those but i will try to get them

Regards,
Eugene

On 28 January 2015 at 12:43, Derek Herman <notifications@github.com> wrote:

> I can't troubleshoot this issue without a verified buyers username, and
> API key. Plus a copy of the previous version of the theme, so I can try and
> duplicate the same environment. If you can supply those things to test this
> issue, my email is derek@valendesigns.com
>
> I also need to know what WP, and PHP versions you're using.
>
> Cheers,
> Derek
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envato/envato-wordpress-toolkit/issues/50#issuecomment-71813950>
> .
>



-- 
Regards,
Eugene

**Comment by valendesigns** [comment]
They can make a temporary API key to test with so they can delete it when they feel like it.

**Comment by Stephen-Cronin** [comment]
Hey guys,

I can provide Derek with the username and API key. Derek is essentially an employee of Envato and I can't see any problem with him having these details so that he can troubleshoot the problem. Derek, I'll send you an email.

Unfortunately however, I can't access an old version of the theme. Eugene, do you have a copy of that? If we don't have it, the only thing I can think of is to change the version number of the theme so it seems like it's an older version.

Cheers,
Stephen

**Comment by valendesigns** [comment]
Thanks Stephen!

**Comment by Stephen-Cronin** [comment]
Email sent! :)

**Comment by valendesigns** [comment]
Awesome! I’ll look into it tomorrow, because it’s 5am here.

Cheers,
Derek

**Comment by tarek009187** [comment]
Hello, is there any update regarding the issue? having trouble due to not able to update my theme.

**Comment by valendesigns** [comment]
Sorry, I don't work weekends and I didn't get to it on Friday. I'll look into it tomorrow though.=

**Comment by valendesigns** [comment]
@tarek009187 The issue appears to be with your themes inconsistent version numbers. Unfortunately, `version_compare` thinks `1.04` and `1.4` are equal. As well, it thinks the current version of `1.4.1` is less than `1.04.3`. The easiest solution is to version up to `1.5.0` and follow major.minor.hotfix versioning from here on out and don't use leading zeros in your versions except for the situations like `1.5.0` then the next hotfix version would be `1.5.1`. There is not much I can do on my end. Sorry!
