### ISSUE TITLE
Nice plugin, but a little heavy..

### ISSUE THREAD

**Issue by JulesWebb** [envato/envato-wordpress-toolkit#53]
Hello

This is some general feedback, or a hopeful feature request.

According to the P3 (Plugin Performance Profiler) plugin the envato wordpress toolkit takes up some pretty heavy resources.  For me the convenience does not outweight trying to keep page loading times down. Below are some results from one of P3's scans

Plugin list:
===========================================
P3 (Plugin Performance Profiler) - 0.0031 sec - 0.13%
LayerSlider - 0.0149 sec - 0.60%
iThemes Security - 0.0837 sec - 3.35%
Cloudflare - 0.0033 sec - 0.13%
Duplicator - 0.0111 sec - 0.45%
__Envato Wordpress Toolkit Master - 1.7488 sec - 69.95%__
WPBakery Visual Composer - 0.2270 sec - 9.08%
Metronet Profile Picture - 0.0115 sec - 0.46%
Monarch Plugin - 0.0094 sec - 0.38%
Revolution Slider - 0.0490 sec - 1.96%
Sb Rss Feed Plus - 0.0041 sec - 0.16%
Simple Image Sizes - 0.0073 sec - 0.29%
UpdraftPlus - Backup/Restore - 0.0174 sec - 0.69%
User Avatar - 0.0008 sec - 0.03%
W3 Total Cache - 0.0662 sec - 2.65%
WooCommerce - 0.1693 sec - 6.77%
Wordfence Security - 0.0439 sec - 1.76%
WP-DBManager - 0.0051 sec - 0.20%
WP Retina 2x - 0.0076 sec - 0.30%
WP Smush.it - 0.0105 sec - 0.42%
 Empty  - 0.0059 sec - 0.24%

Cheers!
jules

**Comment by valendesigns** [comment]
How many themes is the plugin querying for updates for?

**Comment by JulesWebb** [comment]
1 Theme - Specular by Codeless

**Comment by valendesigns** [comment]
What version of the plugin and why is it named `Envato Wordpress Toolkit Master` and not `Envato Wordpress Toolkit`?

**Comment by valendesigns** [comment]
I ran P3 and got these results.
P3 (Plugin Performance Profiler) - 0.0115 sec - 24.74%
Query Monitor - 0.0241 sec - 52.02%
Envato Wordpress Toolkit - 0.0108 sec - 23.24%

**Comment by JulesWebb** [comment]
Version?
Envato WordPress Toolkit Version 1.7.1 

Why master? 
When I downloaded the zip file I didn't rename the extracted folder

+++++++
Two interesting FYI's
I'm not able to deactivate the plugin.  When I click the "deactivate" link the page refreshes, but it still presents the "deactivate" link.  Using FTP I changed the folder name to _envato-wordpress-toolkit-master  It still shows up in the wordpress control panel and it shows the "Activate" link.
++
I updated the Specular theme and ran another report. The plugin took up less resources after the theme was current.

Plugin list:
===========================================
P3 (Plugin Performance Profiler) - 0.0023 sec - 0.18%
LayerSlider - 0.0154 sec - 1.26%
iThemes Security - 0.0797 sec - 6.50%
Duplicator - 0.0086 sec - 0.71%
__Envato Wordpress Toolkit Master - 0.4928 sec - 40.21%__
WPBakery Visual Composer - 0.2207 sec - 18.01%
Metronet Profile Picture - 0.0118 sec - 0.96%
Monarch Plugin - 0.0078 sec - 0.63%
Revolution Slider - 0.0499 sec - 4.07%
Sb Rss Feed Plus - 0.0039 sec - 0.32%
Simple Image Sizes - 0.0050 sec - 0.41%
UpdraftPlus - Backup/Restore - 0.0259 sec - 2.11%
User Avatar - 0.0016 sec - 0.13%
W3 Total Cache - 0.0609 sec - 4.97%
WooCommerce - 0.1642 sec - 13.39%
Wordfence Security - 0.0467 sec - 3.81%
WP-DBManager - 0.0034 sec - 0.28%
WP Retina 2x - 0.0089 sec - 0.72%
WP Smush.it - 0.0127 sec - 1.04%
 Empty  - 0.0036 sec - 0.29%
+++++++

**Comment by valendesigns** [comment]
Rename to `envato-wordpress-toolkit` and rerun the profiler please. I want to see if that is part of the issue.

**Comment by JulesWebb** [comment]
Hi Valendesigns

I renamed to envato-wordpress-toolkit and that makes it so I can activate and deactivate.  

I'm still getting some crazy resource use out of the plugin.  Is P3 a realiable tool? For now I'm going to keep envato toolkit disabled and just enable it when I need to upgrade the them.  

I appreciate your time, thank you. And thank your for creating such a hand tool.

Cheers!
jules

**Comment by valendesigns** [comment]
Even with 2 themes and the plugin itself thinking they need to be updated, I can't get anything close to your numbers. Which leads me to believe there is likely a plugin or server conflict happening. The highest I've got is `0.0313`. I'm not sure how to troubleshoot this issue. You're not the first person to have slow loading times, but I can't reproduce it so it's impossible for me to fix. There has to be an underlying compatibility issue with either your server or a plugin. Which one and how to fix it are not immediately obvious. I need more information.

**Comment by JulesWebb** [comment]
The site I'm having problems with is acutally a server testing situation.  II have duplicate sites set up. 1 on CloudWasy and one on a hostgator shared environment.  The sites are identicle except for the W3 Total Cache settings.  I have the Secular themes installed, but no data except for Wordpress default install.  I have 5 more days of trial period on Cloudways.  I'd be happy to give you login credentials for for both sites if you want to take a look. Send me your email and I'll send login credentials. If you don't have the time, that's ok too.

**Comment by valendesigns** [comment]
It's `derek@valendesigns.com`. So it's not a public site, it's just for testing and I can do stuff like `print_r` & `die` and you'll send the FTP login, as well?

**Comment by valendesigns** [comment]
You sending it?

**Comment by valendesigns** [comment]
My scan returned these results on CloudWays.
```
Envato Wordpress Toolkit - 0.0097 sec - 0.83%
```

While I found that Hostgator can’t properly use P3 it has this message in the help section ...

```
Your site is using the IonCube loader. This has not been known to cause problems with P3.	
Your site is using the Zend Guard loader. This has not been known to cause problems with P3.
```

As, well I deactivate P3 and things started running smoothly. In the process of deactivating and active plugins I found that you have many that add a significant load. However, EWT doesn’t seem to have any effect on your site at all from what I can tell. I would go with CloudWays if I were you, as it seemed like a more responsive server in general. But then I was only in the admin area, so I can speak to the front-end.

**Comment by JulesWebb** [comment]
Hi Derek

Thanks for everything.  Cloudways should be better, I just wanted to see
the results for myself, not just take someone's word for it.
The results on the frontend of hostgator work better than the WP control
panel does, but the page loading is still behind CW.

Thank you for your time, info and experience!
jules

[image: Inline image 22]

^^^^^^^^^^^^^^^^^^^^^^^^^


*Jules Webb * *Freelance Web Developer*

[image: Inline image 10] *425.505.3075* <425.505.3075>

[image: Inline image 19] *hello@JulesWebb.com* <hello@JulesWebb.com>

[image: Inline image 12]
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3LjvR6W7dK_XR5v__JdW2z8P1C56dCtjf6VMVYM02?t=http%3A%2F%2Fjuleswebb.com%2F&si=6605130349150208&pi=8610a4f0-89f7-4caf-93dc-2daf0e8a5639>
 *JulesWebb.com*
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3LjvR6W7dK_XR5v__JdW2z8P1C56dCtjf6VMVYM02?t=http%3A%2F%2Fjuleswebb.com%2F&si=6605130349150208&pi=8610a4f0-89f7-4caf-93dc-2daf0e8a5639>
             [image: Inline image 13]
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3LjvR6W7dK_XR5v__JdW2z8P1C56dCtjf6VMVYM02?t=https%3A%2F%2Fwww.facebook.com%2Fjuleswebb.dev&si=6605130349150208&pi=8610a4f0-89f7-4caf-93dc-2daf0e8a5639>
  [image: Inline image 14]
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3LjvR6W7dK_XR5v__JdW2z8P1C56dCtjf6VMVYM02?t=https%3A%2F%2Ftwitter.com%2FJulesWebb_com&si=6605130349150208&pi=8610a4f0-89f7-4caf-93dc-2daf0e8a5639>
  [image: Inline image 20]
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3LjvR6W7dK_XR5v__JdW2z8P1C56dCtjf6VMVYM02?t=https%3A%2F%2Fplus.google.com%2F108012308357342071526%3Frel%3Dpublisher&si=6605130349150208&pi=8610a4f0-89f7-4caf-93dc-2daf0e8a5639>
  [image: Inline image 16]
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg3LjvR6W7dK_XR5v__JdW2z8P1C56dCtjf6VMVYM02?t=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjuleswebbdotcom&si=6605130349150208&pi=8610a4f0-89f7-4caf-93dc-2daf0e8a5639>



^^^^^^^^^^^^^^^^^^^^^^^^^
