### ISSUE TITLE
Blank white screen after activation

### ISSUE THREAD

**Issue by AndreasReitberger** [envato/envato-wordpress-toolkit#58]
If I try to activate the plugin (latest 1.7.2) then I get a blank white screen and the whole webpage doesn't work anymore. Then I need to delete the plugin from the FTP server and it will work again.

I'm using:

WP 4.1.1 (latest)
Ubuntu V-Server with Parallels Plesk Panel
Memory_Limit: 256 MB

Thanks!

**Comment by valendesigns** [comment]
What's in your error logs?

**Comment by AndreasReitberger** [comment]
Hi,
Thanks for your reply. What error log do you mean? From the server?

**Comment by valendesigns** [comment]
Yes, the error log from the server. Without some indication of why it happened, it's nearly impossible to troubleshoot.

**Comment by AndreasReitberger** [comment]
I checkt the error log and found out that it was a conflict with following plugin.
https://frosty.media/plugins/frosty-media/

I deactivated this plugin and now it works.

Thanks for your help!
