### ISSUE TITLE
Update process not working

### ISSUE THREAD

**Issue by thememount** [envato/envato-wordpress-toolkit#60]
Hello,

We have bundled this plugin in our theme and the theme is updating on most of servers. But currently we faced a strange issue that the theme is not updating and giving blank screen after clicking on the update link.

See attached screenshot. Please let me know if you need more details.

Thanks,
Bob

**Comment by thememount** [comment]
Sorry I missed to attach screenshot. Here it is:

![envato-bug](https://cloud.githubusercontent.com/assets/11554210/6728321/168cb8b4-ce4f-11e4-9a19-5b2a268ef410.png)

**Comment by thememount** [comment]
Here I attached plugin list currently installed. 
![envato-bug-plugins](https://cloud.githubusercontent.com/assets/11554210/6728394/9890be82-ce4f-11e4-801d-9c3deebcadc9.png)

**Comment by valendesigns** [comment]
I'm heading to sleep right now. But I suggest you check the PHP error logs on your server and see if there is any indication of what happened. I'll check back tomorrow to see if you have any new info for me to follow up on. Cheers!

**Comment by thememount** [comment]
Thanks for reply.

I checked for log file but I don't find any log for for error. Also I enabled Debug TRUE via wp-config.php but I don't find any error on the update page and it's still blank.

I am contacting hosting service provider if they can provide me log.

Bob

**Comment by thememount** [comment]
Hello,

The hosting panel doesn't provide me any log section and they could provide me log via email offline so I am little delay to reply you. So finally the problem is solved. The problem is this:

```
PHP Warning:  POST Content-Length of 34944393 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer:
```

I checked this in log and they increased the POST content length and the problem is solved. I think this can help others too.

Thanks,
Bob
