### ISSUE TITLE
Failure to load updates - Recv failure:

### ISSUE THREAD

**Issue by webgod** [envato/envato-wordpress-toolkit#84]
I have tested this issue on several wordpress sites that I have launched with the Envato Toolkit.  Each one spins for a while, then I get this error:

Recv failure: Connection reset by peer

It shows the Settings tab (with that error on top), but not the updates tab

**Comment by pcpbslack** [comment]
I can confirm this on my website. 

Wordpress 4.2.2

Any solution?

**Comment by fitopardo** [comment]
I am experiencing the same, i have deleted the plug in twice and installed again and I have the same response.

**Comment by valendesigns** [comment]
Latest version solves this issue.
